Program         ::= { Statement }

Statement       ::= VarDecl
                 | FuncDecl
                 | ClassDecl
                 | TypeDecl
                 | Assignment
                 | ExpressionStatement

VarDecl         ::= "var" Identifier [ ":" Type ] [ "=" Expression]

FuncDecl        ::= [ "pub" ] function" Identifier "(" [ ParamList ] ")" Block

ClassDecl       ::= [ "pub" ] "class" Identifier "(" [ ParamList ] ")" Block
                 | [ "pub" ] "class" Identifier Block

TypeDecl        ::= [ "pub" ] "type" Identifier "=" Type
                 | [ "pub" ] "type" Identifier ":" GenericFuncType

Assignment      ::= Identifier "=" Expression

ExpressionStatement ::= Expression

Block           ::= "{" { Statement } "}"

ParamList       ::= Param { "," Param } 
Param           ::= Identifier [ ":" Type ] [ "=" Expression ]

Expression      ::= Literal
                 | Identifier
                 | FunctionExpr
                 | TableExpr
                 | IndexAccess
                 | CallExpr
                 | UnaryExpr
                 | BinaryExpr
                 | "(" Expression ")"
                 | Expression "as" Type

FunctionExpr    ::= "function" "(" [ ParamList ] ")" Block

ClassExpr       ::= "class" [ "(" [ ParamList ] ")" ] Block

TableExpr       ::= "{" { TableElement } "}"
TableElement    ::= Expression                      // array-style
                 | Identifier "=" Expression        // key-value style

IndexAccess     ::= Expression "[" Expression "]"

CallExpr        ::= Expression "(" ArgListExpr? ")"
ArgListExpr     ::= Expression { "," Expression }

UnaryExpr       ::= ("not" | "-") Expression

BinaryExpr      ::= Expression BinOp Expression
BinOp           ::= "+" | "-" | "*" | "/" 
                 | ">" | "<" | ">=" | "<=" 
                 | "==" | "~="
                 | "and" | "or"

Literal         ::= StringLiteral | NumberLiteral | "true" | "false" | "nil"

Type            ::= "string" | "number" | "boolean" | "nil"
                 | "(" Type ")" "->" Type
                 | "class" "(" ArgList? ")" Block
                 | Identifier
                 | StructType
                 | GenericType
                 | FuncType

GenericType     ::= "<" Identifier ">" Type

StructType      ::= "struct" "(" StructFields ")"
StructFields    ::= StructField { "," StructField }
StructField     ::= Identifier ":" Type

FuncType        ::= "(" Type ")" "->" Type

GenericFuncType ::= "<" Identifier ">" "(" Identifier ":" Type ")" "->" Type

Identifier      ::= !ReservedWord (Letter { Letter | Digit | "_" })
ReservedWord    ::= "class" | "function" | "var" | "type" | "if" | "else"
                 | "while" | "for" | "true" | "false" | "nil" | "not"
                 | "and" | "or" | "as" | "return"

StringLiteral   ::= "\"" { character } "\""
NumberLiteral   ::= digit { digit } [ "." digit { digit } ]
